# HEEL POINT CALIBRATION

In [1]:
# check coordinate of heel and toe
import cv2
import numpy as np
image_path = 'E:/NUS/5003/HS_frames/AR Gait_P_H016_Free walk_25-11-2022_15-21-44_noAR.o.mp4/frame_0145.png'
image = cv2.imread(image_path)

## Color Recognition

In [47]:

image_path = 'E:/NUS/5003/HS_frames/AR Gait_P_H016_Free walk_25-11-2022_15-21-44_noAR.o.mp4/frame_0145.png'
image = cv2.imread(image_path)
# 将图像从 BGR 转换为 HSV
hsv_image = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)

# 定义宝蓝色的颜色范围（在 HSV 中）
lower_blue = np.array([100, 50, 50])    # 低于这个颜色的值被认为是宝蓝色
upper_blue = np.array([160, 255, 200])  # 高于这个颜色的值被认为是宝蓝色

# 创建掩膜，只保留在蓝色范围内的部分
mask = cv2.inRange(hsv_image, lower_blue, upper_blue)

# 在原始图像上应用掩膜
result = cv2.bitwise_and(image, image, mask=mask)


In [85]:
non_zero_points = cv2.findNonZero(mask)
non_zero_points = non_zero_points.reshape(11463,2)
non_zero_points = non_zero_points[non_zero_points[:, 1] > 800]
heel_idx = np.argmax(non_zero_points[: ,1])
toe_idx = np.argmax(non_zero_points[0,:])
heel_point = non_zero_points[heel_idx, :]  # heel point
toe_point = non_zero_points[toe_idx,:]
print(heel_point)
print(toe_point)
cv2.circle(image, tuple(map(round,toe_point)), radius=25, color=(0, 125, 255), thickness=-1)  # tuple(map(round,max_point))

tuple(map(int,max_point/4))

[ 390 1375]
[301 801]


(97, 343)

In [86]:
resized_image = cv2.resize(image, (270, 480)) # picture 9:16
#resized_result = cv2.resize(result, (360, 640))
cv2.imshow('original_image',resized_image)
#cv2.imshow('blue',resized_result)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [7]:


# 将图像转换为灰度
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

# 进行阈值处理
_, thresholded = cv2.threshold(gray, 80, 222, cv2.THRESH_BINARY)

# 寻找轮廓
contours, _ = cv2.findContours(thresholded, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

# 在原始图像上绘制轮廓
cv2.drawContours(image, contours, -1, (0, 255, 0), 2)
cv2.circle(image,(407,1351),radius = 5, color = (0,0,255),thickness = -1)

# 显示原始图像和带有轮廓的图像

resized_image = cv2.resize(image, (270, 480)) # picture 9:16
resized_result = cv2.resize(thresholded, (360, 640))
cv2.imshow('original_image',resized_image)
cv2.imshow('contours',resized_result)
#cv2.imwrite(os.getcwd()+'/contour_0217.png' ,resized_result )
cv2.waitKey(0)
cv2.destroyAllWindows()

In [8]:
contours,

((array([[[ 394, 1395]],
  
         [[ 397, 1395]]], dtype=int32),
  array([[[ 388, 1377]],
  
         [[ 387, 1378]],
  
         [[ 387, 1379]],
  
         [[ 389, 1379]],
  
         [[ 389, 1378]]], dtype=int32),
  array([[[ 378, 1370]],
  
         [[ 378, 1371]]], dtype=int32),
  array([[[ 407, 1351]]], dtype=int32),
  array([[[ 399, 1323]],
  
         [[ 399, 1324]],
  
         [[ 400, 1324]],
  
         [[ 400, 1323]]], dtype=int32),
  array([[[ 397, 1305]],
  
         [[ 397, 1307]],
  
         [[ 398, 1308]],
  
         [[ 398, 1310]],
  
         [[ 399, 1310]],
  
         [[ 399, 1309]],
  
         [[ 398, 1308]],
  
         [[ 399, 1307]],
  
         [[ 398, 1306]],
  
         [[ 398, 1305]]], dtype=int32),
  array([[[ 396, 1302]],
  
         [[ 396, 1303]],
  
         [[ 397, 1303]],
  
         [[ 397, 1302]]], dtype=int32),
  array([[[ 144, 1256]]], dtype=int32),
  array([[[ 366, 1237]],
  
         [[ 365, 1238]],
  
         [[ 364, 1238]],
  
        

In [9]:
contours[3]

array([[[ 407, 1351]]], dtype=int32)

In [10]:
cv2.drawContours(image, contours[3], -1, (0, 255, 0), 2)
resized_image = cv2.resize(image, (270, 480))
cv2.imshow('original_image',resized_image)

In [45]:
max_point

array([269.75, 343.75])

In [28]:
height, width, channels = image.shape
height, width, channels

(1920, 1080, 3)

In [43]:
1920/4, 1080/4

(480.0, 270.0)